plot:
	gfortran ../arrange.f90 -o arrange
	./arrange
	gnuplot plot.p
	rm arrange
time_1e+0pns:
	gnuplot -e "in_file='1e+0pns.dat'; out_file='time_1e+0pns.jpg'" ../time_curve.p
time_1e-1pns:
	gnuplot -e "in_file='1e-1pns.dat'; out_file='time_1e-1pns.jpg'" ../time_curve.p
time_1e-2pns:
	gnuplot -e "in_file='1e-2pns.dat'; out_file='time_1e-2pns.jpg'" ../time_curve.p
time_1e+1pns:
	gnuplot -e "in_file='1e+1pns.dat'; out_file='time_1e+1pns.jpg'" ../time_curve.p
time_1e+2pns:
	gnuplot -e "in_file='1e+2pns.dat'; out_file='time_1e+2pns.jpg'" ../time_curve.p
time_5e+0pns:
	gnuplot -e "in_file='5e+0pns.dat'; out_file='time_5e+0pns.jpg'" ../time_curve.p
time_5e-1pns:
	gnuplot -e "in_file='5e-1pns.dat'; out_file='time_5e-1pns.jpg'" ../time_curve.p
time_5e-2pns:
	gnuplot -e "in_file='5e-2pns.dat'; out_file='time_5e-2pns.jpg'" ../time_curve.p
time_5e+1pns:
	gnuplot -e "in_file='5e+1pns.dat'; out_file='time_5e+1pns.jpg'" ../time_curve.p
time_5e+2pns:
	gnuplot -e "in_file='5e+2pns.dat'; out_file='time_5e+2pns.jpg'" ../time_curve.p



time_all:
	gnuplot -e "in_file='1e-2pns.dat'; out_file='time_1e-2pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='3e-2pns.dat'; out_file='time_3e-2pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='5e-2pns.dat'; out_file='time_5e-2pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='1e-1pns.dat'; out_file='time_1e-1pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='3e-1pns.dat'; out_file='time_3e-1pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='5e-1pns.dat'; out_file='time_5e-1pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='1e+0pns.dat'; out_file='time_1e+0pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='3e+0pns.dat'; out_file='time_3e+0pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='5e+0pns.dat'; out_file='time_5e+0pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='1e+1pns.dat'; out_file='time_1e+1pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='3e+1pns.dat'; out_file='time_3+1pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='5e+1pns.dat'; out_file='time_5e+1pns.jpg'" ../time_curve.p
	gnuplot -e "in_file='1e+2pns.dat'; out_file='time_1e+2pns.jpg'" ../time_curve.p




